* Veure
https://discuss.huggingface.co/t/most-efficient-multi-label-classifier/9296/2

* The Artificial Guy - MULTI-LABEL TEXT CLASSIFICATION USING BERT AND PYTORCH
https://www.youtube.com/watch?v=f-86-HcYYi8

* Saurabh Anand - BERT for Multi-Label Classification
https://www.youtube.com/watch?v=JjcxZPNZbUY

* KGP Talkie - 5 - Multi-Label Text Classification Model with DistilBERT and Hugging Face Transformers in PyTorch
https://www.youtube.com/watch?v=ZYc9za75Chk

* Fine Tuning BERT for a Multi-Label Classification Problem on Colab - https://medium.com/@abdurhmanfayad_73788/fine-tuning-bert-for-a-multi-label-classification-problem-on-colab-5ca5b8759f3f

* BERT and DistilBERT Models for NLP - https://medium.com/@kumari01priyanka/bert-and-distilbert-model-for-nlp-7352eb16915e

* Choosing the Right Colab Runtime: A Guide for Data Scientists and Analysts - https://drlee.io/choosing-the-right-colab-runtime-a-guide-for-data-scientists-and-analysts-57ee7b7c9638

* distilbert / distilbert-base-uncased - https://huggingface.co/distilbert/distilbert-base-uncased

* "DistilBERT, a distilled version of BERT: smaller, faster, cheaper and lighter" - https://arxiv.org/abs/1910.01108

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!cp /content/drive/MyDrive/TFM-MUECIM/*.py /content
!cp /content/drive/MyDrive/TFM-MUECIM/*.txt /content
!cp /content/drive/MyDrive/TFM-MUECIM/*.csv /content
!cp /content/drive/MyDrive/TFM-MUECIM/*.dat /content
!cp /content/drive/MyDrive/TFM-MUECIM/*.pt /content
!cp /content/drive/MyDrive/TFM-MUECIM/data/datasets/EURLEX57K/*.json /content

In [ ]:
!pip install transformers

In [ ]:
import sys
baseDir = '/content' #/drive/My Drive/TFM-MUECIM'
sys.path.append(baseDir)

Segons el notebook:
Fine-tuning BERT (and friends) for multi-label text classification.ipynb

https://colab.research.google.com/github/NielsRogge/Transformers-Tutorials/blob/master/BERT/Fine_tuning_BERT_(and_friends)_for_multi_label_text_classification.ipynb#scrollTo=HgpKXDfvKBxn  

In [ ]:
import torch

# ensures reproducibility
torch.manual_seed(0)

In [ ]:
from tfm_EURLEX57KDataset import EURLEX57KDataset
from torch.utils.data import random_split

ds = EURLEX57KDataset(baseDir,'ReducedEURLEX57KDataFrame.csv')
fullSetSize = ds.__len__()
trainSetSize = int(fullSetSize * 0.8)
valSetSize = int(fullSetSize * 0.1)
testSetSize = fullSetSize - trainSetSize - valSetSize
print(f'Full set size: {fullSetSize}')
print(f'Train set size: {trainSetSize}')
print(f'Validation set size: {valSetSize}')
print(f'Test set size: {testSetSize}')
trainData, valData, testData = random_split(
    ds,
    [trainSetSize, valSetSize, testSetSize]
)

Full set size: 54382
Train set size: 43505
Validation set size: 5438
Test set size: 5439


In [ ]:
from torch.utils.data import DataLoader

# set batch size
batchSize = 10

# create dataloaders. In case we'll use a more classical pipeline approach
trainDataLoader = DataLoader(trainData, batch_size=batchSize, shuffle=True)
valDataLoader = DataLoader(valData, batch_size=batchSize, shuffle=True)
testDataLoader = DataLoader(testData, batch_size=batchSize, shuffle=True)

In [ ]:
def countNonZeroItems(items):
    nonZero = torch.nonzero(items, as_tuple= True)
    return len(nonZero[0])

In [ ]:
# iterate through val batches
for i, batch in enumerate(valDataLoader):
  print(f'Batch {i}: ')
  batchFileNames = batch.get('fileName')
  batchData = batch.get('input_ids')
  batchAttentionMasks = batch.get('attention_mask')
  batchLabels = batch.get('labels')

  for elem in zip(batchFileNames, batchData, batchAttentionMasks, batchLabels):
    print(f'fileName: {elem[0]}')
    print(f'input_ids (5 first elements):\n{elem[1][0:5]}')
    print(f'attention_masks (5 first elements):\n{elem[2][0:5]}')
    print(f'Nonzero labels:{countNonZeroItems(elem[3])}\n')

  break

print('Done!')

Batch 0: 
fileName: data/datasets/EURLEX57K/train/32010R0503.json
input_ids (5 first elements):
tensor([3222, 7816, 1006, 7327, 1007])
attention_masks (5 first elements):
tensor([1, 1, 1, 1, 1])
Nonzero labels:6

fileName: data/datasets/EURLEX57K/train/32005R1314.json
input_ids (5 first elements):
tensor([ 3222,  7816,  1006, 14925,  1007])
attention_masks (5 first elements):
tensor([1, 1, 1, 1, 1])
Nonzero labels:3

fileName: data/datasets/EURLEX57K/train/32013R0735.json
input_ids (5 first elements):
tensor([ 2473, 14972,  7816,  1006,  7327])
attention_masks (5 first elements):
tensor([1, 1, 1, 1, 1])
Nonzero labels:1

fileName: data/datasets/EURLEX57K/train/32001R1485.json
input_ids (5 first elements):
tensor([ 7816,  1006, 14925,  1007,  2053])
attention_masks (5 first elements):
tensor([1, 1, 1, 1, 1])
Nonzero labels:2

fileName: data/datasets/EURLEX57K/train/32007L0052.json
input_ids (5 first elements):
tensor([ 3222, 16449,  2289,  1013,  4720])
attention_masks (5 first elements

In [ ]:
# bert huggingface pretrained model
import os
from transformers import AutoConfig
from transformers import DistilBertForSequenceClassification
from tfm_ReducedLabelIndex import LabelIndex

labelIndex = LabelIndex(baseDir)

# Gemini. Define a cache directory for Hugging Face models and ensure it exists.
cache_dir = os.path.join(baseDir, 'tfm_cache')
os.makedirs(cache_dir, exist_ok=True)

# Load the configuration with the cache directory.
config = AutoConfig.from_pretrained(
    'distilbert-base-uncased',
    force_download=True,
    cache_dir=cache_dir,
    num_labels=labelIndex.numLabels,
    problem_type='multi_label_classification',
    id2label=labelIndex.id2label,
    label2id=labelIndex.label2id
)


/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
labelIndex.numLabels

453

In [ ]:
# 0 means pretrained fresh model
# 1, 2, 3 ... n. trained epochs from file
actual_epoch_training = 1

if actual_epoch_training == 1:
  modelFile = '20250122_tfm_model.pt'

In [ ]:
# Load the model with the configuration and cache directory.
if actual_epoch_training == 0:
  model = DistilBertForSequenceClassification.from_pretrained(
    'distilbert-base-uncased', # Changed to the correct model identifier
    config=config,  # Pass the configuration to the model.
    cache_dir=cache_dir  # Specify the cache directory again.
  )
else:
  model = torch.load(os.path.join(baseDir,modelFile))

NameError: name 'torch' is not defined

In [ ]:
model

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)


In [ ]:
# forward pass. no training. test case
item = trainData.__getitem__(0)

outputs = model(
    input_ids=item['input_ids'][0:512].unsqueeze(0),
    attention_mask=item['attention_mask'][0:512].unsqueeze(0),
    labels=item['labels'].unsqueeze(0))

In [ ]:
outputs.logits[0]


tensor([-0.0670,  0.0106, -0.0178,  0.0672,  0.0900, -0.0588, -0.0868, -0.0058,
         0.1310,  0.0776,  0.1465,  0.0925, -0.0327,  0.0436,  0.0823, -0.0458,
        -0.0639,  0.0312,  0.0283, -0.0678, -0.0173, -0.1745, -0.1317,  0.0623,
         0.0374,  0.0376, -0.0857, -0.0313, -0.0792, -0.1140,  0.0031,  0.0194,
        -0.0044,  0.0173, -0.1229, -0.0997, -0.0439, -0.0517,  0.0658, -0.0061,
        -0.0298, -0.0333,  0.1592,  0.1266,  0.0595,  0.0221,  0.0656,  0.0618,
        -0.0576,  0.0350, -0.0338,  0.0583,  0.0084, -0.0634,  0.1000, -0.1101,
        -0.0085, -0.0699, -0.0091, -0.0269,  0.0352, -0.0005, -0.1170, -0.0764,
        -0.0155, -0.0036, -0.0050,  0.0590,  0.0065,  0.1318,  0.0317, -0.0406,
         0.0553,  0.0642, -0.0306, -0.0014, -0.0914,  0.0121, -0.0266,  0.0830,
        -0.0558,  0.0037, -0.0013,  0.0489, -0.0113,  0.1120, -0.0187,  0.0094,
         0.1167,  0.0388, -0.0131, -0.0362, -0.0226, -0.1158,  0.1317,  0.0080,
        -0.0316, -0.0126, -0.0353, -0.02

In [ ]:
# source: https://jesusleal.io/2021/04/21/Longformer-multilabel-classification/
# calculate metrics
import numpy as np
from sklearn.metrics import f1_score, roc_auc_score, accuracy_score

sigmoid = torch.nn.Sigmoid()
probs = sigmoid(outputs.logits[0])
threshold = 0.5
y_pred = np.zeros(probs.shape)
y_pred[np.where(probs >= threshold)] = 1
y_true = item['labels'].cpu().numpy() # Convert y_true to a NumPy array
f1_micro_average = f1_score(y_true=y_true, y_pred=y_pred, average='micro')
roc_auc = roc_auc_score(y_true, y_pred, average = 'micro')
accuracy = accuracy_score(y_true, y_pred)

metrics = {'f1': f1_micro_average,
           'roc_auc': roc_auc,
           'accuracy': accuracy}


In [ ]:
metrics  # code test

{'f1': 0.5055187637969095,
 'roc_auc': 0.752212389380531,
 'accuracy': 0.5055187637969095}

In [ ]:
# https://github.com/NielsRogge/Transformers-Tutorials/blob/master/BERT/Fine_tuning_BERT_(and_friends)_for_multi_label_text_classification.ipynb
# https://towardsdatascience.com/evaluating-multi-label-classifiers-a31be83da6ea

import numpy as np
from sklearn.metrics import f1_score, roc_auc_score, accuracy_score
import torch
from transformers import TrainingArguments
from transformers import Trainer
from transformers import EvalPrediction


def multi_label_metrics(predictions, labels, ):
    sigmoid = torch.nn.Sigmoid()
    probs = sigmoid(torch.Tensor(predictions))
    y_pred = np.zeros(probs.shape)
    y_true = labels
    y_pred[np.where(probs >= 0.5)] = 1
    f1_micro_average = f1_score(y_true=y_true, y_pred=y_pred, average='micro')
    roc_auc = roc_auc_score(y_true, y_pred, average = 'micro')
    accuracy = accuracy_score(y_true, y_pred)
    # define dictionary of metrics to return
    metrics = {'f1': f1_micro_average,
               'roc_auc': roc_auc,
               'accuracy': accuracy}
    return metrics

def compute_metrics(p: EvalPrediction):
    preds = p.predictions[0] if isinstance(p.predictions,
            tuple) else p.predictions
    result = multi_label_metrics(
        predictions=preds,
        labels=p.label_ids)
    return result

def metricsForTestSet():
    predictions = trainer.predict(testData)
    preds = predictions.predictions[0] if isinstance(predictions.predictions, tuple) else predictions.predictions
    labels = predictions.label_ids
    testMetrics = multi_label_metrics(predictions=preds, labels=labels)
    print(testMetrics)

# metric
metricName = 'f1'

# training arguments
trainArgs = TrainingArguments(
    'tfm_oputput',
    report_to='none',  # deactivate wandb  reports. Alternative -> TensorBoard
    evaluation_strategy = 'epoch',
    save_strategy = 'epoch',
    learning_rate=2e-5,
    per_device_train_batch_size=batchSize,
    per_device_eval_batch_size=batchSize,
    num_train_epochs=1, # 1 epoch
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model=metricName)

trainer = Trainer(
    model=model,
    args=trainArgs,
    train_dataset=trainData,
    eval_dataset=valData,
    compute_metrics = compute_metrics,
    #data_collator = Data_Processing(),
)

# API-KEY-WAND-LIBRARY: 1bb618394e7e44feab7f79534fa2be428243d1bb

device = 'cuda' if torch.cuda.is_available() else 'cpu'
# Move the model to the correct device before training.
model.to(device)

# epoch 0 - baseline
print('Begin epoch train session - trainer evaluate')
trainer.evaluate()

print('Metrics for test set (before train)')
metricsForTestSet()

# training
print('Epoch train.')
trainer.train()
print('Epoch train done.')

print('End epoch train session - trainer evaluate')
trainer.evaluate()

print('Metrics for test set (after train)')
metricsForTestSet()

print('End epoch train session')

/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(


Begin epoch train session - trainer evaluate


Metrics for test set (before train)
{'f1': 0.015408181277445143, 'roc_auc': 0.5040830380347188, 'accuracy': 0.0}
Epoch train.


Epoch train done.
End epoch train session - trainer evaluate


Metrics for test set (after train)
{'f1': 0.2995355358864254, 'roc_auc': 0.5900190412379849, 'accuracy': 0.013973156830299687}
End epoch train session


In [ ]:
# https://stackoverflow.com/questions/42703500/how-do-i-save-a-trained-model-in-pytorch
import shutil
from datetime import datetime

prefixDate = datetime.today().strftime('%Y%m%d')
fileName = f'{prefixDate}_tfm_model.pt'
modelFullPath = os.path.join(baseDir,fileName)
drivePath = '/content/drive/MyDrive/TFM-MUECIM'
destFullPath = os.path.join(drivePath,fileName)
print('Save model after epoch train session')
torch.save(model, modelFullPath)
shutil.copyfile(modelFullPath, destFullPath)



Save model after epoch train session


'/content/drive/MyDrive/TFM-MUECIM/20250122_tfm_model.pt'