### **TFM - 50 Labels Reduced Dataset. (14/03/2025) (meta-llama/Llama-3.3-70B-Instruct)**

---



---



---

Veure https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct

* See
https://discuss.huggingface.co/t/most-efficient-multi-label-classifier/9296/2

* The Artificial Guy - MULTI-LABEL TEXT CLASSIFICATION USING BERT AND PYTORCH
https://www.youtube.com/watch?v=f-86-HcYYi8

* Saurabh Anand - BERT for Multi-Label Classification
https://www.youtube.com/watch?v=JjcxZPNZbUY

* KGP Talkie - 5 - Multi-Label Text Classification Model with DistilBERT and Hugging Face Transformers in PyTorch
https://www.youtube.com/watch?v=ZYc9za75Chk

* Fine Tuning BERT for a Multi-Label Classification Problem on Colab - https://medium.com/@abdurhmanfayad_73788/fine-tuning-bert-for-a-multi-label-classification-problem-on-colab-5ca5b8759f3f

* BERT and DistilBERT Models for NLP - https://medium.com/@kumari01priyanka/bert-and-distilbert-model-for-nlp-7352eb16915e

* Choosing the Right Colab Runtime: A Guide for Data Scientists and Analysts - https://drlee.io/choosing-the-right-colab-runtime-a-guide-for-data-scientists-and-analysts-57ee7b7c9638

* distilbert / distilbert-base-uncased - https://huggingface.co/distilbert/distilbert-base-uncased

* "DistilBERT, a distilled version of BERT: smaller, faster, cheaper and lighter" - https://arxiv.org/abs/1910.01108

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!cp /content/drive/MyDrive/TFM-MUECIM/*.py /content
!cp /content/drive/MyDrive/TFM-MUECIM/*.txt /content
!cp /content/drive/MyDrive/TFM-MUECIM/*.dat /content
#!cp /content/drive/MyDrive/TFM-MUECIM/*.pt /content
!cp /content/drive/MyDrive/TFM-MUECIM/50LabelsDeepSeekEURLEX57KDataFrame.csv /content

#!cp /content/drive/MyDrive/TFM-MUECIM/*.tar /content
#!cd /content; tar xf data.tar data
#!cd /content/drive/MyDrive/TFM-MUECIM

In [ ]:
!pip install transformers

In [ ]:
import sys
baseDir = '/content' #/drive/My Drive/TFM-MUECIM'
sys.path.append(baseDir)

Segons el notebook:
Fine-tuning BERT (and friends) for multi-label text classification.ipynb

https://colab.research.google.com/github/NielsRogge/Transformers-Tutorials/blob/master/BERT/Fine_tuning_BERT_(and_friends)_for_multi_label_text_classification.ipynb#scrollTo=HgpKXDfvKBxn  

In [ ]:
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'
# Move the model to the correct device before training.

# ensures reproducibility
torch.manual_seed(0)

In [ ]:
from tfm_EURLEX57KDataset import EURLEX57KDataset
from torch.utils.data import random_split

ds = EURLEX57KDataset(baseDir,'50LabelsDeepSeekEURLEX57KDataFrame.csv')
fullSetSize = ds.__len__()
trainSetSize = int(fullSetSize * 0.8)
valSetSize = int(fullSetSize * 0.1)
testSetSize = fullSetSize - trainSetSize - valSetSize
print(f'Full set size: {fullSetSize}')
print(f'Train set size: {trainSetSize}')
print(f'Validation set size: {valSetSize}')
print(f'Test set size: {testSetSize}')
trainData, valData, testData = random_split(
    ds,
    [trainSetSize, valSetSize, testSetSize]
)

Full set size: 29066
Train set size: 23252
Validation set size: 2906
Test set size: 2908


In [ ]:
from torch.utils.data import DataLoader

# set batch size
batchSize = 10

# create dataloaders. In case we'll use a more classical pipeline approach
trainDataLoader = DataLoader(trainData, batch_size=batchSize, shuffle=True)
valDataLoader = DataLoader(valData, batch_size=batchSize, shuffle=True)
testDataLoader = DataLoader(testData, batch_size=batchSize, shuffle=True)

In [ ]:
def countNonZeroItems(items):
    nonZero = torch.nonzero(items, as_tuple= True)
    return len(nonZero[0])

In [ ]:
# iterate through val batches
for i, batch in enumerate(valDataLoader):
  print(f'Batch {i}: ')
  batchFileNames = batch.get('fileName')
  batchData = batch.get('input_ids')
  batchAttentionMasks = batch.get('attention_mask')
  batchLabels = batch.get('labels')

  for elem in zip(batchFileNames, batchData, batchAttentionMasks, batchLabels):
    print(f'fileName: {elem[0]}')
    print(f'input_ids (5 first elements):\n{elem[1][0:5]}')
    print(f'attention_masks (5 first elements):\n{elem[2][0:5]}')
    print(f'Nonzero labels:{countNonZeroItems(elem[3])}\n')

  break

print('Done!')

Batch 0: 
fileName: data/datasets/EURLEX57K/train/32010R0455.json
input_ids (5 first elements):
tensor([84627, 31454,   343, 41809,    11])
attention_masks (5 first elements):
tensor([1, 1, 1, 1, 1])
Nonzero labels:2

fileName: data/datasets/EURLEX57K/train/31993R2932.json
input_ids (5 first elements):
tensor([84627, 31454,   343,    39,  3255])
attention_masks (5 first elements):
tensor([1, 1, 1, 1, 1])
Nonzero labels:1

fileName: data/datasets/EURLEX57K/train/32014R0018.json
input_ids (5 first elements):
tensor([84627, 68043, 31454,   343, 41809])
attention_masks (5 first elements):
tensor([1, 1, 1, 1, 1])
Nonzero labels:2

fileName: data/datasets/EURLEX57K/train/31999R0831.json
input_ids (5 first elements):
tensor([84627, 31454,   343,  3255,    11])
attention_masks (5 first elements):
tensor([1, 1, 1, 1, 1])
Nonzero labels:1

fileName: data/datasets/EURLEX57K/train/31997D0516.json
input_ids (5 first elements):
tensor([ 5106,    17, 24254,    17,  3255])
attention_masks (5 first ele

In [ ]:
# bert huggingface pretrained model
import os
from transformers import AutoConfig
#from transformers import BertForSequenceClassification
from tfm_50LabelsLabelIndex import LabelIndex

labelIndex = LabelIndex(baseDir)

# Gemini. Define a cache directory for Hugging Face models and ensure it exists.
cache_dir = os.path.join(baseDir, 'tfm_cache')
os.makedirs(cache_dir, exist_ok=True)

# Load the configuration with the cache directory.
config = AutoConfig.from_pretrained(
    'deepseek-ai/DeepSeek-V3',
    force_download=True,
    cache_dir=cache_dir,
    num_labels=labelIndex.numLabels,
    problem_type='multi_label_classification',
    id2label=labelIndex.id2label,
    label2id=labelIndex.label2id
)


/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/1.73k [00:00<?, ?B/s]

The repository for deepseek-ai/DeepSeek-V3 contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co/deepseek-ai/DeepSeek-V3.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] y


configuration_deepseek.py:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/deepseek-ai/DeepSeek-V3:
- configuration_deepseek.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.


config.json:   0%|          | 0.00/1.73k [00:00<?, ?B/s]

In [ ]:
labelIndex.numLabels

50

In [ ]:
# 0 means pretrained fresh model
# 1, 2, 3 ... n. trained epochs from file
last_epoch_trained = 0

if last_epoch_trained == 1:
  modelFile = '20250216_50L_tfm_BERT_model_epoch_1.pt'
if last_epoch_trained == 2:
  modelFile = '20250216_50L_tfm_BERT_model_epoch_2.pt'
if last_epoch_trained == 3:
  modelFile = '20250216_50L_tfm_BERT_model_epoch_3.pt'
if last_epoch_trained == 4:
  modelFile = '20250216_50L_tfm_BERT_model_epoch_4.pt'
if last_epoch_trained == 5:
  modelFile = '20250216_50L_tfm_BERT_model_epoch_5.pt'
if last_epoch_trained == 6:
  modelFile = '20250216_50L_tfm_BERT_model_epoch_6.pt'
if last_epoch_trained == 7:
  modelFile = '20250216_50L_tfm_BERT_model_epoch_7.pt'
if last_epoch_trained == 8:
  modelFile = '20250216_50L_tfm_BERT_model_epoch_8.pt'
if last_epoch_trained == 9:
  modelFile = '20250216_50L_tfm_BERT_model_epoch_9.pt'
if last_epoch_trained == 10:
  modelFile = '20250216_50L_tfm_BERT_model_epoch_10.pt'
if last_epoch_trained == 11:
  modelFile = '20250216_50L_tfm_BERT_model_epoch_11.pt'



In [ ]:
# https://stackoverflow.com/questions/79424312/deepseek-huggingface-model-loading-issue

from transformers import AutoModelForCausalLM

config = AutoConfig.from_pretrained("deepseek-ai/DeepSeek-R1", trust_remote_code=True)
del config.quantization_config

# Load the model with the configuration and cache directory.
if last_epoch_trained == 0:
  model = AutoModelForCausalLM.from_pretrained(
   "deepseek-ai/DeepSeek-R1", # Changed to the correct model identifier
   config=config, # Pass the configuration to the model.
   trust_remote_code=True,
   cache_dir=cache_dir  # Specify the cache directory again.)
  )
else:
  model = torch.load(os.path.join(baseDir,modelFile), map_location=torch.device(device))

config.json:   0%|          | 0.00/1.73k [00:00<?, ?B/s]

configuration_deepseek.py:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/deepseek-ai/DeepSeek-R1:
- configuration_deepseek.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.


modeling_deepseek.py:   0%|          | 0.00/75.8k [00:00<?, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/deepseek-ai/DeepSeek-R1:
- modeling_deepseek.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.


model.safetensors.index.json:   0%|          | 0.00/8.90M [00:00<?, ?B/s]

model-00001-of-000163.safetensors:   0%|          | 0.00/5.23G [00:00<?, ?B/s]

model-00002-of-000163.safetensors:   0%|          | 0.00/4.30G [00:00<?, ?B/s]

model-00003-of-000163.safetensors:   0%|          | 0.00/4.30G [00:00<?, ?B/s]

model-00004-of-000163.safetensors:   0%|          | 0.00/4.30G [00:00<?, ?B/s]

model-00005-of-000163.safetensors:   0%|          | 0.00/4.30G [00:00<?, ?B/s]

KeyboardInterrupt: 

In [ ]:
model

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(28996, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e

In [ ]:

# forward pass. no training. test case
# item = trainData.__getitem__(0)

# outputs = model(
#    input_ids=item['input_ids'][0:512].unsqueeze(0),
#    attention_mask=item['attention_mask'][0:512].unsqueeze(0),
#    labels=item['labels'].unsqueeze(0))

In [ ]:
# outputs.logits[0]


In [ ]:
# source: https://jesusleal.io/2021/04/21/Longformer-multilabel-classification/
# calculate metrics
# import numpy as np
# from sklearn.metrics import f1_score, roc_auc_score, accuracy_score

# sigmoid = torch.nn.Sigmoid()
# probs = sigmoid(outputs.logits[0])
# threshold = 0.5
# y_pred = np.zeros(probs.shape)
# y_pred[np.where(probs >= threshold)] = 1
# y_true = item['labels'].cpu().numpy() # Convert y_true to a NumPy array
# f1_micro_average = f1_score(y_true=y_true, y_pred=y_pred, average='micro')
# roc_auc = roc_auc_score(y_true, y_pred, average = 'micro')
# accuracy = accuracy_score(y_true, y_pred)

# metrics = {'f1': f1_micro_average,
#           'roc_auc': roc_auc,
#           'accuracy': accuracy}


In [ ]:
# metrics  # code test

In [ ]:
# https://github.com/NielsRogge/Transformers-Tutorials/blob/master/BERT/Fine_tuning_BERT_(and_friends)_for_multi_label_text_classification.ipynb
# https://towardsdatascience.com/evaluating-multi-label-classifiers-a31be83da6ea

import numpy as np
from sklearn.metrics import f1_score, roc_auc_score, accuracy_score
import torch
from transformers import TrainingArguments
from transformers import Trainer
from transformers import EvalPrediction


def multi_label_metrics(predictions, labels, ):
    sigmoid = torch.nn.Sigmoid()
    probs = sigmoid(torch.Tensor(predictions))
    y_pred = np.zeros(probs.shape)
    y_true = labels
    y_pred[np.where(probs >= 0.5)] = 1
    f1_micro_average = f1_score(y_true=y_true, y_pred=y_pred, average='micro')
    roc_auc = roc_auc_score(y_true, y_pred, average = 'micro')
    accuracy = accuracy_score(y_true, y_pred)
    # define dictionary of metrics to return
    metrics = {'f1': f1_micro_average,
               'roc_auc': roc_auc,
               'accuracy': accuracy}
    return metrics

def compute_metrics(p: EvalPrediction):
    preds = p.predictions[0] if isinstance(p.predictions,
            tuple) else p.predictions
    result = multi_label_metrics(
        predictions=preds,
        labels=p.label_ids)
    return result

def metricsForTestSet():
    predictions = trainer.predict(testData)
    preds = predictions.predictions[0] if isinstance(predictions.predictions, tuple) else predictions.predictions
    labels = predictions.label_ids
    testMetrics = multi_label_metrics(predictions=preds, labels=labels)
    print(testMetrics)

# metric
metricName = 'f1'

# training arguments
trainArgs = TrainingArguments(
    'tfm_oputput',
    report_to='none',  # deactivate wandb  reports. Alternative -> TensorBoard
    evaluation_strategy = 'epoch',
    save_strategy = 'epoch',
    learning_rate=2e-5,
    per_device_train_batch_size=batchSize,
    per_device_eval_batch_size=batchSize,
    num_train_epochs=1, # 3 epochs
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model=metricName)

trainer = Trainer(
    model=model,
    args=trainArgs,
    train_dataset=trainData,
    eval_dataset=valData,
    compute_metrics = compute_metrics,
    #data_collator = Data_Processing(),
)

# API-KEY-WAND-LIBRARY: 1bb618394e7e44feab7f79534fa2be428243d1bb

device = 'cuda' if torch.cuda.is_available() else 'cpu'
# Move the model to the correct device before training.
model.to(device)

# epoch 0 - baseline
print(f'Begin epoch {last_epoch_trained + 1} train session - trainer evaluate')
trainer.evaluate()

print('Metrics for test set (before train)')
metricsForTestSet()

# training
print('Epoch train.')
trainer.train()
print('Epoch train done.')

print('End epoch train session - trainer evaluate')
trainer.evaluate()

print('Metrics for test set (after train)')
metricsForTestSet()

print('End epoch train session')

Begin epoch 12 train session - trainer evaluate


/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(


Metrics for test set (before train)
{'f1': 0.8394675019577134, 'roc_auc': 0.9120205379971229, 'accuracy': 0.7008253094910591}
Epoch train.


Epoch train done.
End epoch train session - trainer evaluate


Metrics for test set (after train)
{'f1': 0.8388773388773388, 'roc_auc': 0.9134876074465559, 'accuracy': 0.7028885832187071}
End epoch train session


In [ ]:
# https://stackoverflow.com/questions/42703500/how-do-i-save-a-trained-model-in-pytorch
import shutil
from datetime import datetime

prefixDate = datetime.today().strftime('%Y%m%d')
fileName = f'{prefixDate}_50L_tfm_BERT_model_epoch_{last_epoch_trained + 1}.pt'
modelFullPath = os.path.join(baseDir,fileName)
drivePath = '/content/drive/MyDrive/TFM-MUECIM'
destFullPath = os.path.join(drivePath,fileName)
print('Save model after epoch train session')
torch.save(model, modelFullPath)
shutil.copyfile(modelFullPath, destFullPath)



Save model after epoch train session


'/content/drive/MyDrive/TFM-MUECIM/20250216_50L_tfm_BERT_model_epoch_12.pt'